/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 MounTripElement.glb MounTripElement_2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/MounTripElement.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes['3D_1_-_1'].geometry} material={materials['Wood 1']} position={[-15.65, 7.5, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/MounTripElement.glb')
