/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 MounTripElement_8.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/MounTripElement_8.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh
          geometry={nodes['3D_8_-_8'].geometry}
          material={materials.Wood}
          position={[-15.27, 7.5, 0.7]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/MounTripElement_8.glb')
