/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 MounTripElement_4.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/MounTripElement_4.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.01]} scale={0}>
        <mesh geometry={nodes['3D_4_-_4'].geometry} material={materials['Wood 1']} position={[-13.63, 6.92, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/MounTripElement_4.glb')
